name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        REACT_APP_PUBLIC_ID: ${{ secrets.REACT_APP_PUBLIC_ID }}
        REACT_APP_SERVICE_ID: ${{ secrets.REACT_APP_SERVICE_ID }}

    - name: Deploy
      uses: iiam-health-official/main_web_front@release/v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
