name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        CI: false
        REACT_APP_PUBLIC_ID: ${{ secrets.REACT_APP_PUBLIC_ID }}
        REACT_APP_SERVICE_ID: ${{ secrets.REACT_APP_SERVICE_ID }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
